/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32l476xx.h"
#include <stdio.h>
// create a led delay. Just a rough estimate
// for one second delay
int boton=1;
int con=0;
int t2=0;
volatile uint32_t i = 0;
volatile uint32_t code[10];
/*************************************************
* function declarations
*************************************************/
int main(void);
void GPIO_init(void);
void Ext_init(void);
void TIMER_init(void);
void morse(void);
/*************************************************
* external interrupt handler
*************************************************/
void TIM2_IRQHandler(void)
{

    // clear interrupt status
    if (TIM2->DIER & 0x01) {
        if (TIM2->SR & 0x01) {
            TIM2->SR &= ~(1U << 0);
        }
    }
		con +=1;
}
void EXTI15_10_IRQHandler(void)
{
	//Check if the interrupt came from exti13
	if(EXTI->PR1 & (1 <<13)){
	//Cambio de valor para la variable que indica
	//cuando se presiona  y cuando se libera
				boton ^=0x1;
			// Clear pending bit
		EXTI->PR1 = 0x00002000;
	}
}
int main(void)
{
	//Se inicializa las GPIO que se van a usar (Puerto A y C)
	GPIO_init();
	// Se configura la interrupción externa
	Ext_init();
	//Inicializamos el TIMER que marcara el tiempo de la secuencia
	TIMER_init();
	morse();

	while(1)
	{

	}

	__asm__("NOP"); // Assembly inline can be used if needed
	return 0;
}

void GPIO_init(void){
	RCC->AHB2ENR |= 0x00000005;
	// Make GPIOD Pin13 as input pin (bits 27:26 in MODER register)
	GPIOC->MODER &= 0xFFFFFFFF;		// Clear bits 27, 26 for P13
	GPIOC->MODER &= 0xF3FFFFFF;		// Write 00 to bits 27, 26 for P13
}
void Ext_init(void){
    // enable SYSCFG clock
    	RCC->APB2ENR |= 0x1;
    	// Writing a 0b0010 to pin13 location ties PC13 to EXT4
    	SYSCFG->EXTICR[3] |= 0x20; // Write 0002 to map PC13 to EXTI4
    	// Choose either rising edge trigger (RTSR1) or falling edge trigger (FTSR1)
    	EXTI->RTSR1 |= 0x2000;   // Enable rising edge trigger on EXTI4
    	EXTI->FTSR1 |= 0x2000;	 // Enable falling edge trigger on EXTI4
    	// Mask the used external interrupt numbers.
    	EXTI->IMR1 |= 0x2000;    // Mask EXTI4
    	// Set Priority for each interrupt request
    	NVIC->IP[EXTI15_10_IRQn] = 0x10; // Priority level 1
    	// enable EXT0 IRQ from NVIC
    	NVIC_EnableIRQ(EXTI15_10_IRQn);
}
void TIMER_init(void){
    // enable TIM2 clock (bit0)
    RCC->APB1ENR1 |= (1<<0);
    TIM2->PSC = 7999;
    TIM2->ARR = 40;
    // Update Interrupt Enable
    TIM2->DIER |= (1 << 0);
    NVIC_SetPriority(TIM2_IRQn, 2); // Priority level 2
    // enable TIM2 IRQ from NVIC
    NVIC_EnableIRQ(TIM2_IRQn);
    // Enable Timer 2 module (CEN, bit0)
    TIM2->CR1 |= (1 << 0);
}
 void morse(void){
//Lock es una bandera que permite
	 int lock=0;
	 while(1){
//Al presionarse el boton, se detecta un flanco y la interrupción cambia las variables para entrar
//al primer if solo una vez
		 if ((boton==0)&(lock==0)){ //Estado: Inicio señal
			 t2=con;
			 lock=1;
		 }
//Cuando se libera el boton entra al segundo if
		 if ((t2>0)&(boton==1)){ //Estado: Final Señal
// si el tiempo que el boton paso es menor a 5 segundos, es un punto.
			 //Estado: Determinacion
			 if (((con-t2)>10)&((con-t2)<30)){
				 code[i]='.';
				 i++;
			 }
// Si es mayor, es una linea.
			 else{
				 code[i]='_';
				 i++;
			 }
//Entonces se reinicia la variable de tiempo t2
			 t2=0;
			 lock=0;
		 }
	 }
 }
