/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*************************************************
* Libraries include
*************************************************/
#include "stm32l476xx.h"
#include <stdbool.h>
/*************************************************
* definition variables
*************************************************/
#define COUNT 10

bool up = true;
/*************************************************
* function prototyping
*************************************************/

/*************************************************
* external interrupt handler
*************************************************/
void TIM2_IRQHandler(void)
{

    // clear interrupt status
    if (TIM2->DIER & 0x01) {
        if (TIM2->SR & 0x01) {
            TIM2->SR &= ~(1U << 0);
        }
    }

    GPIOA->ODR ^= 0x0020;


}

/*************************************************
* Main
*************************************************/
int main(void)
{
	// enable GPIOA clock
	RCC->AHB2ENR = 0x1;
	// Make GPIOA Pin5 as output pin (bits 1:0 in MODER register)
	GPIOA->MODER &= 0xFFFFF3FF;
	GPIOA->MODER |= 0x00000400;
	// enable TIM2 clock
	RCC->APB1ENR1 |= (1 << 0);

	// fCK_PSC / (PSC[15:0] + 1)
	// 40 Khz / n + 1 =  timer clock speed
	TIM2->PSC = 40680;
	// set total count
	TIM2->ARR = COUNT;

	// Update Interrupt Enable
	TIM2->DIER |= (1 << 0);

	NVIC_SetPriority(TIM2_IRQn, 2); // Priority level 2
	// enable TIM2 IRQ from NVIC
	NVIC_EnableIRQ(TIM2_IRQn);

	// Enable Timer 2 module (CEN, bit0)
	TIM2->CR1 |= (1 << 0);

	GPIOA->ODR ^= 0x0020;

	while(1)
	{

	}

	__asm__("NOP"); // Assembly inline can be used if needed
	return 0;
}
